### PR TITLE
adding timeslot data as part of the timeslot partial

### PR DESCRIPTION
**Pull request by olieydt**
To fix issue [#348](https://github.com/tastyigniter/TastyIgniter/issues/348)

### CODE REVIEW

**Comment by sampoyigi** [comment]
If you look in the markup a new child element is added when you toggle the order types instead of replacing the #local-timeslot element. Moving just the `data-time-slot` should work but you'll also have to make changes to the local.timeslot.js file.

**Comment by olieydt** [comment]
Im not sure what you mean here, is there a benefit to moving just the `data-time-slot`?

**Comment by sampoyigi** [comment]
With the changes, you'll end up with this every time the order type changes

```
<div id="local-timeslot" .....>
  <div id="local-timeslot" ......>
    <div id="local-timeslot" ......>
```

Moving just the `data-time-slot` means the timeslot data still gets updated when the order type changes

**Comment by olieydt** [comment]
Ah yeah I noticed that, thank you for clarifying. Ive made the changes and added a change in timeslot.js. These changes are needed for the the localbox.php change from [earlier](https://github.com/tastyigniter/ti-ext-cart/pull/1)

**Pull request merged**
