### PR TITLE
Fill column width with menu

### PR DESCRIPTION
**Pull request by ryanmitchell**
Suggested change on the theme. Now that the timeslot selection is repositioned it would make sense to make the dropdown fill the column width.

### CODE REVIEW

**Review by sampoyigi — APPROVED** [review]

**Comment by sampoyigi** [comment]
Push the compiled css file as well.

**Comment by ryanmitchell** [comment]
Would love to but I get compile errors due to missing icons etc… you need to talk me through your folder set up some time so I can replicate!

**Comment by sampoyigi** [comment]
Sure, when you're ready

**Comment by sampoyigi** [comment]
Merged too quick.. We can actually place the date and time fields next to each other since we have more space now..

**Comment by ryanmitchell** [comment]
No problem - I've done that by changing the html here:
https://github.com/tastyigniter/ti-ext-local/pull/33

**Pull request merged**
