### PR TITLE
Update webpack.mix.js

### PR DESCRIPTION
**Pull request by nyousefzai**
making sure assets get a unique hash appended to the assets filenames every time make changes to those files after they are recompiled.

### CODE REVIEW

**Comment by sampoyigi** [comment]
Can you add more context to what this PR solves?

We only use webpack for updating dependencies nothing to do with compiling, we use a modified version of Assetic PHP library for that.

**Comment by nyousefzai** [comment]
so basically To assist with long-term caching, Laravel Mix provides the mix.version() method to enable file hashing, such as app.js?id=8e5c48eadbfdd5458ec6. This is useful for cache-busting purposes.

Imagine that your server automatically caches scripts for one year to improve performance. That's great, but each time you make a change to your application code, you need some way to instruct the server to bust the cache. This is typically done through the use of query strings or file hashing.
here are more [details](https://laravel-mix.com/docs/6.0/versioning)

**Comment by sampoyigi** [comment]
I understand what `mix.version()` does but not what it solves in this case. As I mentioned, we don't use webpack for compiling assets, it's only used to maintain dependencies (copy assets from node_modules into the app) and IIRC the cache bursting thing only applies when compiling assets?

**Comment by nyousefzai** [comment]
then, in that case, it's unnecessary. I am closing the pull request.

**Comment by sampoyigi** [comment]
Thank you anyways!

**Pull request closed without merging**
